
CREATE DATABASE LOCADORA;
GO

USE LOCADORA;


CREATE TABLE EMPRESA(
 idEmpresa TINYINT PRIMARY KEY IDENTITY(1,1),
 nomePessoa VARCHAR(20) NOT NULL
);


CREATE TABLE MARCA (
 idMarca TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeMarca VARCHAR(20) NOT NULL
);


CREATE TABLE MODELO(
 idModelo TINYINT PRIMARY KEY IDENTITY(1,1),
 idMarca TINYINT FOREIGN KEY REFERENCES MARCA(idMarca),
 nomeModelo VARCHAR(15) NOT NULL
);


CREATE TABLE VEICULO(
 idVeiculo TINYINT PRIMARY KEY IDENTITY(1,1),
 idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
 idModelo TINYINT FOREIGN KEY REFERENCES MODELO(idModelo),
 placaVeiculo CHAR(8) NOT NULL

);
