CREATE DATABASE PCLINICS;
GO

USE PCLINICS;
GO

CREATE TABLE CLINICA (
 idClinica TINYINT PRIMARY KEY IDENTITY (1,1),
 razaoSocial VARCHAR(35),
 endereço VARCHAR(100),
);

CREATE TABLE DONO(
 idDono TINYINT PRIMARY KEY IDENTITY (1,1),
 nomeDono VARCHAR(30)
);

CREATE TABLE TIPOPET(
 idTipoPet TINYINT PRIMARY KEY IDENTITY (1,1),
 Titulo VARCHAR(30)
);

CREATE TABLE RACA(
 idRaca  TINYINT PRIMARY KEY IDENTITY (1,1),
 idTipoPet TINYINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
 nomeRaca VARCHAR(30)
);

CREATE TABLE VETERINARIO(
 idVeterinario  TINYINT PRIMARY KEY IDENTITY (1,1),
 idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
 CRMV VARCHAR(3),
 nomeVeterinario VARCHAR(30) NOT NULL
);

CREATE TABLE PET(
 idPet  TINYINT PRIMARY KEY IDENTITY (1,1),
 idDono TINYINT FOREIGN KEY REFERENCES DONO(idDono),
 idRaca TINYINT FOREIGN KEY REFERENCES RACA(idRaca),
 nomeRaca VARCHAR(30), 
 telefone VARCHAR(15)
);

CREATE TABLE ATENDIMENTO(
 idAtendimento TINYINT PRIMARY KEY IDENTITY (1,1),
 idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
 idPet TINYINT FOREIGN KEY REFERENCES PET(idPet),
 dataAtendimento VARCHAR(15),
 descricao VARCHAR(50)
);

ALTER TABLE VETERINARIO
ADD  nomeVeterinario VARCHAR(30) NOT NULL;

ALTER TABLE VETERINARIO
DROP COLUMN nomeVeterinario;

ALTER TABLE VETERINARIO
ADD nomeVeterinario VARCHAR(30) NOT NULL;

ALTER TABLE PET
DROP COLUMN nomeRaca;

ALTER TABLE PET
ADD nomePet VARCHAR(30) NOT NULL;
