
SELECT * FROM CLINICA

SELECT * FROM DONO

SELECT * FROM TIPOPET

SELECT * FROM RACA

SELECT * FROM VETERINARIO

SELECT * FROM PET

SELECT * FROM ATENDIMENTO

--LISTAR TODOS OS VETERINARIOS (NOME E CRMV) DE UMA CLINICA (RAZAO SOCIAL)

SELECT  razaoSocial, nomeVeterinario, CRMV
FROM CLINICA
LEFT JOIN VETERINARIO
ON CLINICA.idVeterinario = VETERINARIO.idVeterinario;

